/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BecomeAStockistRouteImport } from './routes/become-a-stockist'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FlowSimulatorRouteImport } from './routes/flow-simulator'
import { Route as ManualsRouteImport } from './routes/manuals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RangesRouteImport } from './routes/ranges'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SparesRouteImport } from './routes/spares'
import { Route as StockistsRouteImport } from './routes/stockists'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as RangeSlugRouteImport } from './routes/range.$slug'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RegisterSlugRouteImport } from './routes/register.$slug'
import { Route as SparesIndexRouteImport } from './routes/spares.index'
import { Route as SparesProductIdRouteImport } from './routes/spares.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAStockistRoute = BecomeAStockistRouteImport.update({
  id: '/become-a-stockist',
  path: '/become-a-stockist',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowSimulatorRoute = FlowSimulatorRouteImport.update({
  id: '/flow-simulator',
  path: '/flow-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsRoute = ManualsRouteImport.update({
  id: '/manuals',
  path: '/manuals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RangesRoute = RangesRouteImport.update({
  id: '/ranges',
  path: '/ranges',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SparesRoute = SparesRouteImport.update({
  id: '/spares',
  path: '/spares',
  getParentRoute: () => rootRouteImport,
} as any)
const StockistsRoute = StockistsRouteImport.update({
  id: '/stockists',
  path: '/stockists',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RangeSlugRoute = RangeSlugRouteImport.update({
  id: '/range/$slug',
  path: '/range/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterSlugRoute = RegisterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegisterRoute,
} as any)
const SparesIndexRoute = SparesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SparesRoute,
} as any)
const SparesProductIdRoute = SparesProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => SparesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/become-a-stockist': typeof BecomeAStockistRoute
  '/cookies': typeof CookiesRoute
  '/flow-simulator': typeof FlowSimulatorRoute
  '/manuals': typeof ManualsRoute
  '/privacy': typeof PrivacyRoute
  '/ranges': typeof RangesRoute
  '/register': typeof RegisterRouteWithChildren
  '/spares': typeof SparesRouteWithChildren
  '/stockists': typeof StockistsRoute
  '/terms': typeof TermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/range/$slug': typeof RangeSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/spares/$productId': typeof SparesProductIdRoute
  '/register/': typeof RegisterIndexRoute
  '/spares/': typeof SparesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/become-a-stockist': typeof BecomeAStockistRoute
  '/cookies': typeof CookiesRoute
  '/flow-simulator': typeof FlowSimulatorRoute
  '/manuals': typeof ManualsRoute
  '/privacy': typeof PrivacyRoute
  '/ranges': typeof RangesRoute
  '/stockists': typeof StockistsRoute
  '/terms': typeof TermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/range/$slug': typeof RangeSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/spares/$productId': typeof SparesProductIdRoute
  '/register': typeof RegisterIndexRoute
  '/spares': typeof SparesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/become-a-stockist': typeof BecomeAStockistRoute
  '/cookies': typeof CookiesRoute
  '/flow-simulator': typeof FlowSimulatorRoute
  '/manuals': typeof ManualsRoute
  '/privacy': typeof PrivacyRoute
  '/ranges': typeof RangesRoute
  '/register': typeof RegisterRouteWithChildren
  '/spares': typeof SparesRouteWithChildren
  '/stockists': typeof StockistsRoute
  '/terms': typeof TermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/range/$slug': typeof RangeSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/spares/$productId': typeof SparesProductIdRoute
  '/register/': typeof RegisterIndexRoute
  '/spares/': typeof SparesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/become-a-stockist'
    | '/cookies'
    | '/flow-simulator'
    | '/manuals'
    | '/privacy'
    | '/ranges'
    | '/register'
    | '/spares'
    | '/stockists'
    | '/terms'
    | '/product/$slug'
    | '/range/$slug'
    | '/register/$slug'
    | '/spares/$productId'
    | '/register/'
    | '/spares/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/become-a-stockist'
    | '/cookies'
    | '/flow-simulator'
    | '/manuals'
    | '/privacy'
    | '/ranges'
    | '/stockists'
    | '/terms'
    | '/product/$slug'
    | '/range/$slug'
    | '/register/$slug'
    | '/spares/$productId'
    | '/register'
    | '/spares'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/become-a-stockist'
    | '/cookies'
    | '/flow-simulator'
    | '/manuals'
    | '/privacy'
    | '/ranges'
    | '/register'
    | '/spares'
    | '/stockists'
    | '/terms'
    | '/product/$slug'
    | '/range/$slug'
    | '/register/$slug'
    | '/spares/$productId'
    | '/register/'
    | '/spares/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BecomeAStockistRoute: typeof BecomeAStockistRoute
  CookiesRoute: typeof CookiesRoute
  FlowSimulatorRoute: typeof FlowSimulatorRoute
  ManualsRoute: typeof ManualsRoute
  PrivacyRoute: typeof PrivacyRoute
  RangesRoute: typeof RangesRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  SparesRoute: typeof SparesRouteWithChildren
  StockistsRoute: typeof StockistsRoute
  TermsRoute: typeof TermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  RangeSlugRoute: typeof RangeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-stockist': {
      id: '/become-a-stockist'
      path: '/become-a-stockist'
      fullPath: '/become-a-stockist'
      preLoaderRoute: typeof BecomeAStockistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-simulator': {
      id: '/flow-simulator'
      path: '/flow-simulator'
      fullPath: '/flow-simulator'
      preLoaderRoute: typeof FlowSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals': {
      id: '/manuals'
      path: '/manuals'
      fullPath: '/manuals'
      preLoaderRoute: typeof ManualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranges': {
      id: '/ranges'
      path: '/ranges'
      fullPath: '/ranges'
      preLoaderRoute: typeof RangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spares': {
      id: '/spares'
      path: '/spares'
      fullPath: '/spares'
      preLoaderRoute: typeof SparesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stockists': {
      id: '/stockists'
      path: '/stockists'
      fullPath: '/stockists'
      preLoaderRoute: typeof StockistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/range/$slug': {
      id: '/range/$slug'
      path: '/range/$slug'
      fullPath: '/range/$slug'
      preLoaderRoute: typeof RangeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/$slug': {
      id: '/register/$slug'
      path: '/$slug'
      fullPath: '/register/$slug'
      preLoaderRoute: typeof RegisterSlugRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/spares/': {
      id: '/spares/'
      path: '/'
      fullPath: '/spares/'
      preLoaderRoute: typeof SparesIndexRouteImport
      parentRoute: typeof SparesRoute
    }
    '/spares/$productId': {
      id: '/spares/$productId'
      path: '/$productId'
      fullPath: '/spares/$productId'
      preLoaderRoute: typeof SparesProductIdRouteImport
      parentRoute: typeof SparesRoute
    }
  }
}

interface RegisterRouteChildren {
  RegisterSlugRoute: typeof RegisterSlugRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterSlugRoute: RegisterSlugRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface SparesRouteChildren {
  SparesProductIdRoute: typeof SparesProductIdRoute
  SparesIndexRoute: typeof SparesIndexRoute
}

const SparesRouteChildren: SparesRouteChildren = {
  SparesProductIdRoute: SparesProductIdRoute,
  SparesIndexRoute: SparesIndexRoute,
}

const SparesRouteWithChildren =
  SparesRoute._addFileChildren(SparesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BecomeAStockistRoute: BecomeAStockistRoute,
  CookiesRoute: CookiesRoute,
  FlowSimulatorRoute: FlowSimulatorRoute,
  ManualsRoute: ManualsRoute,
  PrivacyRoute: PrivacyRoute,
  RangesRoute: RangesRoute,
  RegisterRoute: RegisterRouteWithChildren,
  SparesRoute: SparesRouteWithChildren,
  StockistsRoute: StockistsRoute,
  TermsRoute: TermsRoute,
  ProductSlugRoute: ProductSlugRoute,
  RangeSlugRoute: RangeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
